### ISSUE TITLE
Technical Design

### ISSUE THREAD

**Issue by TuxUbuntu** [Butylkus/Tatiana#3]
# Архитектура

Предлагаю привести к следующей архитектуре:

Backend - твоя программа на питоне с cli API
Frontend - программа на php которая проксирует запросы из web в твой python скрипт
Client - клиент, со статическими файлами, которые дргуют Frontend

# Протоколы

### Client -> Frontend

HTTP POST на адресс **/api/vx**

В body запросу будет лежать JSON с параметрами запроса

формат запроса:

```javascript
{
  "action": "", // выбираем action
  "data": { // посылаем данные в обработчик
    // ...
  }
}
```

### Frontend -> Client

ответ типа application/json содержащиё данные ответа

структура данных ответа:

```javascript
{
  "messages": [ { "type": "error", "text": "" } ],
  "data": {} // результат с данными
}
```

### Frontend -> Backend

cli для твоего робота

### Backend -> Frontend

желательно какой-то структуризированный ответ.

**Comment by Butylkus** [comment]
https://github.com/Butylkus/Tatiana/tree/master/frontend2.0
Это сам шаблон плюс файл с настройками, его можно колбасить, но он должен быть понятен чайнику.
Сейчас опишу протокол сообщения между скриптами.

**Comment by Butylkus** [comment]
Залил описание форматов и алгоритмов работы с файлами (читаем файл протокол).
